"""Generate workflows/docs/ and workflows/README.md from the workflows themselves.

Every graph already carries its documentation as a MarkdownNote on its own canvas, which
is the copy that is actually in front of you while you work. So that note is the source
and everything here is derived from it — a hand-written second copy would drift from the
canvas within a week, and the canvas is the one you would believe.

    python tools/workflow_docs.py            rewrite docs/ and README.md
    python tools/workflow_docs.py --check    exit 1 if either is out of date

Run it with a Python that can import this package (it needs torch, pillow and requests —
the same environment ComfyUI runs it in). The generated pages carry which folders each
graph reads and writes, and that comes from the live node definitions rather than from
guessing at positional widget values, so the tool refuses to write rather than quietly
emitting thinner pages from an environment where the import failed.
"""

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKFLOWS = os.path.join(ROOT, "workflows")
DOCS = os.path.join(WORKFLOWS, "docs")

FAMILIES = [
    ("flux2", "FLUX.2", "Black Forest Labs endpoints, one image at a time."),
    ("stability", "Stability", "The control endpoints, each studied alone, chained through folders."),
    ("tarot", "Tarot", "Deck-shaped work: whole runs, staged runs, and single-card technique studies."),
]

# Nodes that spend money. One call each per execution, except the sweep node, which makes
# as many as its grid comes to.
PAID_PREFIXES = ("BFLFlux2", "StabAI")
FREE_EXCEPTIONS = {"BFLFlux2LoadImageFromPath"}
VARIABLE_COST = {"BFLFlux2BatchVariations"}

READ_WIDGETS = ("directory", "input_path", "anchor_dir", "definition_path", "load_from",
                "path", "overlay_path")
WRITE_WIDGETS = ("output_dir", "save_definition_to", "save_to")

BANNER = ("<!-- Generated by tools/workflow_docs.py from the workflow's own note. "
          "Edit the MarkdownNote inside the graph, then re-run the tool. -->")


def node_meta():
    """{node type: {"widgets": [...], "list_outputs": [bool, ...]}} from the live node
    definitions, or {} when the package cannot be imported."""
    try:
        sys.path.insert(0, os.path.dirname(ROOT))
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "_sp", os.path.join(ROOT, "__init__.py"), submodule_search_locations=[ROOT])
        pack = importlib.util.module_from_spec(spec)
        sys.modules["_sp"] = pack
        spec.loader.exec_module(pack)
    except Exception as exc:
        print("Could not import the node package: {}: {}".format(type(exc).__name__, exc),
              file=sys.stderr)
        print("Run this with the Python that runs ComfyUI, or any env with the packages in "
              "requirements.txt.", file=sys.stderr)
        return None

    meta = {}
    opaque = {"IMAGE", "MASK", "TAROT_DECK", "TAROT_STYLE", "TAROT_RULES"}
    for key, cls in pack.NODE_CLASS_MAPPINGS.items():
        try:
            spec_ = cls.INPUT_TYPES()
        except Exception:
            continue
        row = []
        for section in ("required", "optional"):
            for name, entry in spec_.get(section, {}).items():
                kind, options = (entry + ({},))[:2] if isinstance(entry, tuple) else (entry, {})
                if isinstance(kind, list):
                    row.append(name)
                elif kind in opaque or options.get("forceInput"):
                    continue
                else:
                    row.append(name)
                    if name in ("seed", "noise_seed") and kind == "INT":
                        row.append("control_after_generate")
        flags = getattr(cls, "OUTPUT_IS_LIST", ())
        meta[key] = {
            "widgets": row,
            "list_outputs": [bool(f) for f in flags] or [False] * len(cls.RETURN_TYPES),
        }
    return meta


def fed_by_list(node, nodes_by_id, links_by_id, meta):
    """True when this node is wired to a list output, so ComfyUI runs it once per item.

    This is the difference between a graph that makes one call and one that makes
    seventy-eight, and counting nodes alone cannot see it.
    """
    for entry in node.get("inputs", []):
        link = links_by_id.get(entry.get("link"))
        if not link:
            continue
        source = nodes_by_id.get(link[1])
        flags = meta.get(source["type"], {}).get("list_outputs", []) if source else []
        if link[2] < len(flags) and flags[link[2]]:
            return True
    return False


def read_workflow(path, meta):
    widgets = {key: value["widgets"] for key, value in meta.items()}
    data = json.load(open(path))
    nodes = data.get("nodes", [])
    nodes_by_id = {n["id"]: n for n in nodes}
    links_by_id = {l[0]: l for l in data.get("links", [])}
    notes = [n["widgets_values"][0] for n in nodes
             if n["type"] == "MarkdownNote" and n.get("widgets_values")]
    counts = Counter(n["type"] for n in nodes)

    paid = 0
    variable = False
    per_item = False
    for node in nodes:
        kind = node["type"]
        if kind in VARIABLE_COST:
            variable = True
        elif kind.startswith(PAID_PREFIXES) and kind not in FREE_EXCEPTIONS:
            paid += 1
            if fed_by_list(node, nodes_by_id, links_by_id, meta):
                per_item = True

    reads, writes = set(), set()
    for node in nodes:
        row = widgets.get(node["type"])
        if not row:
            continue
        for name, value in zip(row, node.get("widgets_values", [])):
            if not isinstance(value, str) or not value.strip():
                continue
            if name in READ_WIDGETS:
                reads.add(value.strip())
            elif name in WRITE_WIDGETS:
                writes.add(value.strip())

    note = "\n\n".join(notes).strip()
    title, summary = describe(note, os.path.basename(path))
    return {
        "path": path,
        "name": os.path.splitext(os.path.basename(path))[0],
        "family": os.path.basename(os.path.dirname(path)),
        "title": title,
        "summary": summary,
        "note": note,
        "nodes": len(nodes),
        "links": len(data.get("links", [])),
        "counts": counts,
        "paid": paid,
        "variable": variable,
        "per_item": per_item,
        "reads": sorted(reads),
        "writes": sorted(writes),
    }


def describe(note, filename):
    """The note's first heading is the title; its first paragraph is the summary.

    A paragraph, not a line — notes are hard-wrapped, so taking one line cuts the summary
    off mid-sentence.
    """
    default = os.path.splitext(filename)[0]
    title, paragraph = default, []
    for line in note.splitlines():
        stripped = line.strip()
        heading = re.match(r"^#+\s+(.*)$", stripped)
        if heading:
            if title == default:
                title = heading.group(1).strip()
            if paragraph:
                break
            continue
        if not stripped:
            if paragraph:
                break
            continue
        # A table, list or quote is not a summary. A bullet is "- " or "* " with the
        # space; "**Read this**" is bold and is very often exactly the summary.
        bullet = re.match(r"^([-*+]\s|\d+\.\s|>|\|)", stripped)
        if bullet and not paragraph:
            continue
        paragraph.append(stripped)

    summary = re.sub(r"\*\*|`|\*", "", " ".join(paragraph)).strip()
    if len(summary) > 200:
        cut = summary[:200]
        stop = max(cut.rfind(". "), cut.rfind("; "))
        summary = (cut[:stop + 1] if stop > 80 else cut.rsplit(" ", 1)[0] + "…")
    return title, summary


def cost_label(entry):
    if entry["variable"]:
        return "{} + a sweep".format(entry["paid"]) if entry["paid"] else "a sweep"
    if not entry["paid"]:
        return "free"
    if entry["per_item"]:
        return "{} per input".format(entry["paid"])
    return str(entry["paid"])


def chain_map(entries):
    """Who writes a folder somebody else reads."""
    writers = defaultdict(list)
    for entry in entries:
        for folder in entry["writes"]:
            writers[folder.rstrip("/")].append(entry["name"])
    feeds, fed_by = defaultdict(set), defaultdict(set)
    for entry in entries:
        for folder in entry["reads"]:
            for source in writers.get(folder.rstrip("/"), []):
                if source != entry["name"]:
                    fed_by[entry["name"]].add(source)
                    feeds[source].add(entry["name"])
    return feeds, fed_by


def doc_for(entry, feeds, fed_by):
    rel = os.path.relpath(entry["path"], WORKFLOWS).replace(os.sep, "/")
    out = [BANNER, "", "# {}".format(entry["title"]), "",
           "**Workflow:** [`{0}`](../{0})".format(rel), "",
           "| | |", "| --- | --- |",
           "| Family | `{}` |".format(entry["family"]),
           "| Nodes | {} |".format(entry["nodes"]),
           "| Links | {} |".format(entry["links"]),
           "| Paid API calls per run | **{}** |".format(cost_label(entry))]
    if entry["reads"]:
        out.append("| Reads | {} |".format(" · ".join("`%s`" % r for r in entry["reads"])))
    if entry["writes"]:
        out.append("| Writes | {} |".format(" · ".join("`%s`" % w for w in entry["writes"])))
    if fed_by.get(entry["name"]):
        out.append("| Fed by | {} |".format(" · ".join(
            "[%s](%s.md)" % (n, n) for n in sorted(fed_by[entry["name"]]))))
    if feeds.get(entry["name"]):
        out.append("| Feeds | {} |".format(" · ".join(
            "[%s](%s.md)" % (n, n) for n in sorted(feeds[entry["name"]]))))
    # The page already carries the title as its own heading; repeating the note's opening
    # heading directly under it just reads as a stutter.
    body = entry["note"]
    first = body.splitlines()[0].strip() if body else ""
    if re.match(r"^#+\s+", first) and re.sub(r"^#+\s+", "", first) == entry["title"]:
        body = "\n".join(body.splitlines()[1:]).lstrip("\n")

    out += ["", "---", "", body, "", "---", "", "## Nodes in this graph", "",
            "| Node | × |", "| --- | --- |"]
    for kind, count in sorted(entry["counts"].items()):
        out.append("| `{}` | {} |".format(kind, count))
    out.append("")
    return "\n".join(out)


def index_for(entries, feeds, fed_by):
    total_paid = sum(e["paid"] for e in entries if not e["per_item"])
    out = [BANNER, "", "# Workflows", "",
           "{} ready-made graphs. Drag a `.json` onto the ComfyUI canvas, or use "
           "**Workflow → Open**.".format(len(entries)), "",
           "**Every graph documents itself on its own canvas.** The MarkdownNote inside each "
           "one is the real documentation — it is the copy in front of you while you work, and "
           "everything under [`docs/`](docs/) is generated from it. Read either; they cannot "
           "disagree.", "",
           "> **Calls** is how many billing nodes a run hits before you bypass anything. "
           "**Ctrl+B** on a node drops it from the run and passes its input straight through. "
           "*per input* means the node is fed a list, so it fires once for every image handed "
           "to it — a folder's worth, or a deck's, which is the difference between 3 calls and "
           "234. *a sweep* means the Batch / Sweep node, whose count is its own grid.", ""]

    for folder, label, blurb in FAMILIES:
        rows = [e for e in entries if e["family"] == folder]
        if not rows:
            continue
        out += ["## {}".format(label), "", blurb, "",
                "| Workflow | Calls | What it does |", "| --- | --- | --- |"]
        for entry in sorted(rows, key=lambda e: e["name"]):
            rel = os.path.relpath(entry["path"], WORKFLOWS).replace(os.sep, "/")
            out.append("| [`{}`]({}) · [docs](docs/{}.md) | {} | {} |".format(
                entry["name"], rel, entry["name"], cost_label(entry), entry["summary"]))
        out.append("")

    chains = [(source, sorted(targets)) for source, targets in sorted(feeds.items())]
    if chains:
        out += ["## What feeds what", "",
                "There is no workflow-calls-a-workflow in ComfyUI. What crosses a file "
                "boundary is a folder, and these are the folders that already line up — one "
                "graph writes where another reads:", ""]
        for source, targets in chains:
            out.append("- [`{}`](docs/{}.md) → {}".format(
                source, source, ", ".join("[`%s`](docs/%s.md)" % (t, t) for t in targets)))
        out += ["", "Any other pairing works the same way: point the reader's `directory` at "
                "the writer's `output_dir`.", ""]

    out += ["## Adding one", "",
            "1. Drop the `.json` into the family folder it belongs to — `flux2/`, "
            "`stability/` or `tarot/`.",
            "2. Give it a **MarkdownNote** whose first heading is its title and whose first "
            "paragraph says what it does in a sentence. That note becomes its documentation.",
            "3. Run `python tools/workflow_docs.py`.", "",
            "That is the whole process. This index and every page under `docs/` are generated "
            "by scanning the folders, so nothing has to be registered anywhere by hand — a "
            "list you have to remember to update is a list that goes stale. "
            "`python tools/workflow_docs.py --check` exits non-zero when they are behind.", "",
            "Filenames keep their family prefix (`stability-01-sketch.json`, not "
            "`01-sketch.json`) because ComfyUI shows the bare filename in its tab, and with "
            "several graphs open the prefix is the only thing telling them apart.", "",
            "---", "",
            "{} graphs. Running every fixed-cost one once comes to {} calls; the *per input* "
            "and *sweep* graphs are on top of that and depend on what you feed them.".format(
                len(entries), total_paid), ""]
    return "\n".join(out)


def build():
    meta = node_meta()
    if meta is None:
        return None, None
    paths = []
    for folder, _label, _blurb in FAMILIES:
        directory = os.path.join(WORKFLOWS, folder)
        if os.path.isdir(directory):
            paths += [os.path.join(directory, f) for f in sorted(os.listdir(directory))
                      if f.endswith(".json")]
    entries = [read_workflow(path, meta) for path in paths]
    feeds, fed_by = chain_map(entries)
    files = {os.path.join(DOCS, entry["name"] + ".md"): doc_for(entry, feeds, fed_by)
             for entry in entries}
    files[os.path.join(WORKFLOWS, "README.md")] = index_for(entries, feeds, fed_by)
    return entries, files


def main(argv=None):
    args = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    args.add_argument("--check", action="store_true",
                      help="report staleness instead of writing")
    options = args.parse_args(argv)

    entries, files = build()
    if files is None:
        return 2
    if not entries:
        print("No workflows found under {}".format(WORKFLOWS))
        return 1

    stale = []
    for path, text in sorted(files.items()):
        try:
            current = open(path).read()
        except OSError:
            current = None
        if current != text:
            stale.append(os.path.relpath(path, ROOT))
            if not options.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w").write(text)

    if options.check:
        for path in stale:
            print("stale: {}".format(path))
        print("{} workflow(s), {} file(s) out of date".format(len(entries), len(stale)))
        return 1 if stale else 0

    for path in stale:
        print("wrote {}".format(path))
    print("{} workflow(s) documented, {} file(s) changed".format(len(entries), len(stale)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
